inherit_gem:
  theforeman-rubocop:
    - lenient.yml
    - minitest.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - '*.spec'
    - 'extras/**/*'
    - 'locale/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'db/seeds.d/*'

Layout/DotPosition:
  EnforcedStyle: 'trailing'

Layout/LineLength:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FormatString:
  EnforcedStyle: percent

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/foreman_acd/app_instance.rb'
