require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.1
  Exclude:
    - '*.spec'
    - 'extras/**/*'
    - 'locale/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*' # context blocks can be long

# Just so it looks like core Foreman
Style/HashSyntax:
  EnforcedStyle: hash_rockets

Layout/DotPosition:
  EnforcedStyle: 'trailing'

Rails/ActionFilter:
  EnforcedStyle: action

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FormatStringToken:
  EnforcedStyle: template

Rails/SkipsModelValidations:
  Enabled: false

Metrics:
  Enabled: false

