language: ruby
install:
  - unset BUNDLE_GEMFILE
  - cd ..
  - git clone https://github.com/theforeman/foreman.git -b ${FOREMAN_CORE_BRANCH} --depth 1
  - cd foreman
  - echo "gemspec :path => '../foreman_acd'" > bundler.d/foreman_acd.local.rb
  - ln -s settings.yaml.test config/settings.yaml
  - ln -s database.yml.example config/database.yml
  - bundle install --jobs=3 --retry=3 --without journald development postgresql mysql2 console
  - bundle exec rake db:migrate RAILS_ENV=test
  - pushd ../foreman_acd
  - npm install
  - popd
script:
  - bundle exec rubocop ../foreman_acd
  - bundle exec rake test:foreman_acd
  - pushd ../foreman_acd
  - npm test
  - popd
env:
  global:
    - TESTOPTS=-v
matrix:
  include:
    - rvm: 2.4
      env: FOREMAN_CORE_BRANCH=1.24-stable
    - rvm: 2.5
      env: FOREMAN_CORE_BRANCH=1.24-stable
addons:
  apt:
    packages:
    - nodejs
    - git
    - libsqlite3-dev
    - zlib1g-dev
    - libvirt-dev
