export const APPLICATION_INSTANCE_REPORT_INIT =
  'APPLICATION_INSTANCE_REPORT_INIT';
export const APPLICATION_INSTANCE_REPORT_SET_ACTIVE_HOST =
  'APPLICATION_INSTANCE_REPORT_SET_ACTIVE_HOST';
export const APPLICATION_INSTANCE_REPORT_LOAD_REPORT_REQUEST =
  'APPLICATION_INSTANCE_REPORT_LOAD_REPORT_REQUEST';
export const APPLICATION_INSTANCE_REPORT_LOAD_REPORT_SUCCESS =
  'APPLICATION_INSTANCE_REPORT_LOAD_REPORT_SUCCESS';
export const APPLICATION_INSTANCE_REPORT_LOAD_REPORT_FAILURE =
  'APPLICATION_INSTANCE_REPORT_LOAD_REPORT_FAILURE';
