export const APPLICATION_DEFINITION_IMPORT_INIT =
  'INIT_APPLICATION_DEFINITION_IMPORT_INIT';
export const APPLICATION_DEFINITION_IMPORT_SERVICE_EDIT_CHANGE =
  'APPLICATION_DEFINITION_IMPORT_SERVICE_EDIT_CHANGE';
export const APPLICATION_DEFINITION_IMPORT_FILE_FAILURE =
  'APPLICATION_DEFINITION_IMPORT_FILE_FAILURE';
export const APPLICATION_DEFINITION_IMPORT_FILE_REQUEST =
  'APPLICATION_DEFINITION_IMPORT_FILE_REQUEST';
export const APPLICATION_DEFINITION_IMPORT_FILE_SUCCESS =
  'APPLICATION_DEFINITION_IMPORT_FILE_SUCCESS';
export const APPLICATION_DEFINITION_IMPORT_CLOSE_ALERT_MODAL =
  'APPLICATION_DEFINITION_IMPORT_CLOSE_ALERT_MODAL';
