export const PUPPET_ENV_REQUEST = 'PUPPET_ENV_REQUEST';
export const PUPPET_ENV_SUCCESS = 'PUPPET_ENV_SUCCESS';
export const PUPPET_ENV_FAILURE = 'PUPPET_ENV_FAILURE';

export const LIFECYCLE_ENV_REQUEST = 'LIFECYCLE_ENV_REQUEST';
export const LIFECYCLE_ENV_SUCCESS = 'LIFECYCLE_ENV_SUCCESS';
export const LIFECYCLE_ENV_FAILURE = 'LIFECYCLE_ENV_FAILURE';

export const INIT_PARAMETER_SELECTION = 'INIT_PARAMETER_SELECTION';

export const PARAMETER_DELETE = 'PARAMETER_DELETE';
export const PARAMETER_ADD = 'PARAMETER_ADD';
export const PARAMETER_EDIT_ACTIVATE = 'PARAMETER_EDIT_ACTIVATE';
export const PARAMETER_EDIT_CONFIRM = 'PARAMETER_EDIT_CONFIRM';
export const PARAMETER_EDIT_CHANGE = 'PARAMETER_EDIT_CHANGE';
export const PARAMETER_EDIT_CANCEL = 'PARAMETER_EDIT_CANCEL';
export const PARAMETER_SORT = 'PARAMETER_SORT';
