export const EXISTING_HOST_SELECTION_INIT = 'EXISTING_HOST_SELECTION_INIT';
export const EXISTING_HOST_SELECTION_LOAD_HOSTS_SUCCESS =
  'EXISTING_HOST_SELECTION_LOAD_HOSTS_SUCCESS';
export const EXISTING_HOST_SELECTION_LOAD_HOSTS_FAILURE =
  'EXISTING_HOST_SELECTION_LOAD_HOSTS_FAILURE';
export const EXISTING_HOST_SELECTION_SELECTION_CHANGED =
  'EXISTING_HOST_SELECTION_SELECTION_CHANGED';
