---
name: Ruby Tests
"on":
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rubocop:
    uses: theforeman/actions/.github/workflows/rubocop.yml@v0

  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: env | sort

  test:
    name: Ruby
    needs: rubocop
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: foreman_acd
      matrix_exclude: '[{"ruby": "3.0", "node": "14"}]'
